# This file was automatically generated by the CUTLASS 3.5.1 Python interface (https://github.com/nvidia/cutlass/python)

from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension
import sysconfig
import os

lib_dir = sysconfig.get_path("purelib")
# lib_dir might be something like "/usr/local/lib/python3.12/dist-packages"
# or, if you use anaconda, something like '/home/myusername/miniconda3/envs/myenvname/lib/python3.12/dist-packages'

setup(
    name='i4mm',
    ext_modules=[
        CUDAExtension('i4mm', [
            'i4mm.cpp',
            'i4mm_kernel.cu',
        ],
        include_dirs=[
            os.path.join(lib_dir, 'cutlass_library/source/include'), 
            os.path.join(lib_dir, 'cutlass_library/source/tools/util/include'),
        ],
        extra_compile_args={
            'cxx': ['-std=c++17'],
            'nvcc': ['-std=c++17', ],
        },
        libraries=['cuda']
        ),
    ],
    cmdclass={
        'build_ext': BuildExtension
    })

